spring.application.name=courseManagementProject

spring.datasource.url=jdbc:mysql://localhost:3306/course_management_project
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=mukesh
spring.security.user.password=12345

spring.jwt.secret=this_is_my_secret_key_that_is_being_used_for_access_token_generation_1234567890